### ISSUE TITLE
Ease of Use on Linux

### ISSUE THREAD

**Issue by antler5** [MeteorStudioASU/lcc#11]
Hi! I've just got a couple feedback notes regarding the linux build script and Readme. I run Fedora 32, and initially ended up rebooting into windows to try this out because I couldn't figure it out last on linux night. I'm not incredibly tech-savy, but am no stranger to building from source either. I understand that with the wide range of distros folks run, linux support can be hard to streamline, but I think this awesome project should ideally be straight-forward to install even for those without experience tinkering, and hope my feedback can help; 

Building with cmake as currently recommended in the readme tried to build a binary with Alsa, Jack, and Pulse libs, none of which it could find, but a hackernews thread suggested building with `g++ -O2 -march=native -mtune=native -D__LINUX_PULSE__ -D__LINUX_ALSA__ -D__UNIX_JACK__ lcc_rtaudio.cpp RtAudio.cpp -o lcc -pthread -ljack -lasound  -lpulse-simple -lpulse`.
Removing the Jack/Alsa bits and installing pulse's devel packages and was all I needed to do.

I ran into another issue during setup. The directions suggest creating a sink with `module-combine-sink`, joining the system output to the speakers much like the virtual cable does in the Windows instructions, but the issue is that RAudio pipes the sink monitor to the speakers, and the sink itself (being a combined sink module with the stereo speakers configured as a slave) *also* outputs to the speakers, creating the audio equivalent of seeing double. I fiddled with my pulseaudio inputs and outputs for a bit, but once I was sure no configuration was going to fix this, I resolved it by instead using `module-null-sink` to make a sink without any slaves to serve as our virtual cable.

As mentioned, I'm not incredibly tech-savy, and curiously can hear a distinct difference between outputting to my speakers and outputting through the null-sink even with LCC set to Off, so not everything is quite right (it's boom-ier, for lack of a better desc.; maybe the jack and alsa deps were important), but this has been my experience building and running LCC on Fedora. I absolutely love the effect and the strong center channel it creates. 

I look forward to information on Parameter Tuning, as my only remaining complaint is that the enhanced echos and reverberations (as well as "ambient" center-channel sounds like white-noise, water, and wind sounds in mixes) tend to be much *too* clear, and can sound grainy, gritty, or harsh. I imagine I could EQ it out, but would be thrilled to have a deeper understanding of what's happening and whether any of the provided settings could help (LLC_decaygain?). Thanks for doing this awesome work c:

**Comment by adct-the-experimenter** [comment]
I wrote the linux instructions.

Thank you for the correction with pulseaudio.
I maintain a fork that is developed on linux. 
I added updates there according to your feedback.

https://github.com/adct-the-experimenter/lcc

I may make a pull request in the near future. 

Edit: 
I can't do much about your build situation since I would have to look at your linux environment to see why
cmake can't find ALSA or JACK.  

I am glad to hear that you have a working build.

Currently by default, lcc is just built for all 3 if you are on linux and also have JACK and pulseaudio.

option(RTAUDIO_API_ALSA "Build ALSA API" ${LINUX})
option(RTAUDIO_API_PULSE "Build PulseAudio API" ${pulse_FOUND})
option(RTAUDIO_API_JACK "Build JACK audio server API" ${HAVE_JACK})

Cmake can override these variables with -D.

To turn off compiling for ALSA and JACK, pass these arguments to cmake.
cmake .. -DRTAUDIO_API_ALSA=OFF -DRTAUDIO_API_JACK=OFF
