### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by vessenes** [MeteorStudioASU/lcc#3]
This is super cool. Proof: my 13 year old got me to install it on his laptop within minutes of hearing it. 

I'm curious about a roadmap; the c++ code is pretty simple. I can tell I already want it running on non-laptop speakers; right now, I don't have a way to calculate out what settings lcc should use for non-macbook speakers -- the linked google sheet doesn't work for me, or I don't understand it. 

At any rate, I love this! Thanks for publishing it.

**Comment by mattlane66** [comment]
So cool to hear this. Sound is much more subtle than video for most people. Really awesome to hear younger people can pick up on the value proposition. 
The Google Sheet should work. Does it open for you? 
We have not opened parameters for LCC, so that calculator is not necessary right now. 
That said, we preconfigured/tuned LCC with what we feel are the ideal parameters. Please read the speaker placement and speaker type recommendations in our white paper. In short, try to avoid horizontal speaker arrays (multiple speakers per channel like soundbars) and keep, ideally point source drivers, like the KEF LS50 or The Ones by Genelec, less than 2'0"-3'0" apart.
